name: Lint with pyright

on:
  push:
    paths:
      - 'src/**.py'
  pull_request:
    paths:
      - 'src/**.py'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Fetch tags
        run: git fetch --tags --depth 1
      - name: Set up Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'
      - name: Install pyright
        run: pip install pyright
      - name: Install dpygt
        run: pip install .
      - name: Run pyright
        run: pyright
