name: Lint with pyright

on:
  push:
    paths:
      - 'src/**.py'
  pull_request:
    paths:
      - 'src/**.py'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'
      - run: pip install pyright
      - run: pip install .
      - run: pyright
